VERTICAL_TILE_NUMBER = 120
HORIZONTAL_TILE_NUMBER = 360
TILE_SIZE = 16
LV_WIDTH, LV_HEIGHT = TILE_SIZE * \
    HORIZONTAL_TILE_NUMBER, TILE_SIZE*VERTICAL_TILE_NUMBER
SC_WIDTH, SC_HEIGHT = TILE_SIZE * 60, TILE_SIZE*40
FPS = 60

DOG_WIDTH = 67
DOG_HEIGHT = 61
